apiVersion: v2
appVersion: 1.26.1
description: mlflow helm package
name: mlflow
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - mlflow
home: https://github.com/combinator-ml/charts/tree/master/charts/stable/mlflow
icon: https://avatars.githubusercontent.com/u/39938107?s=200&v=4
sources:
  - https://github.com/combinator-ml/charts
maintainers:
  - name: Phil Winder
    email: phil@winder.ai
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
