#
# IMPORTANT NOTE
#
# This chart inherits from k8s-at-home's common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

modeldynamics:
  internal:
    project:
      name: ""
  settings:
    mlflow:
      bucket: ""

mlflow:
  bucket: s3://your-s3-bucket #pragma: helix.modeldynamics.ai/expose

image:
  # -- image repository
  repository: ghcr.io/combinator-ml/mlflow

# -- Main environment variables. Template enabled.
env:
  # -- Set the container timezone.
  TZ: UTC
  DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "common.names.fullname" .}}-postgresql/{{ .Values.postgresql.auth.database }}?sslmode=disable
  MLFLOW_ARTIFACT_ROOT: "{{ default .Values.mlflow.bucket .Values.modeldynamics.settings.mlflow.bucket }}"

envFrom:
  - secretRef:
      name: aws-credentials

args:
  - --host=0.0.0.0
  - --backend-store-uri=$(DATABASE_URL)
  - --default-artifact-root=$(MLFLOW_ARTIFACT_ROOT)

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5000

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: true
  auth:
    username: mlflow-user
    password: mlflow-pass
    database: mlflow-db
  persistence:
    enabled: false
