#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

mlflow:
  scheme: "http"
  name: "mlflow" # pragma: helix.modeldynamics.ai/expose
  domain: "svc.cluster.local"
  port: "5000"

image:
  # -- image repository
  repository: jupyter/minimal-notebook
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  # -- Include the mlflow tracking URI just in case jupyter needs to connect to mlflow
  MLFLOW_NAME: "{{ .Values.mlflow.name }}"
  MLFLOW_HOST: '{{ ternary "" (printf "%s-" .Values.modeldynamics.internal.project.name) (empty .Values.modeldynamics.internal.project.name) }}{{ tpl .Values.env.MLFLOW_NAME . }}'
  MLFLOW_TRACKING_URI: "{{ .Values.mlflow.scheme }}://{{ tpl .Values.env.MLFLOW_HOST . }}.{{ .Release.Namespace }}.{{ .Values.mlflow.domain }}:{{ .Values.mlflow.port }}"
  GRANT_SUDO: "yes"
  # - name: MLFLOW_S3_ENDPOINT_URL
  # value: "http://minio.minio.svc.cluster.local:9000" # TODO: parameterize based on configured storage target

envFrom:
  - secretRef:
      name: aws-credentials # pragma: helix.modeldynamics.ai/expose
      optional: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8888

# -- Configure configMaps for the chart here.
# Additional configMaps can be added by adding a dictionary key similar to the 'config' object.
# @default -- See values.yaml
configmap:
  config:
    # -- Enables or disables the configMap
    enabled: true
    # -- Labels to add to the configMap
    labels: {}
    # -- Annotations to add to the configMap
    annotations: {}
    # -- configMap data content. Helm template enabled.
    data:
      jupyter_notebook_config.py: |
        # See https://jupyter-notebook.readthedocs.io/en/stable/config.html#options
        # For a full list of options
        # SECURITY - auth is disabled by default, please set a password
        c.NotebookApp.token = ''
        c.NotebookApp.password = ''

# -- Configure persistence for the chart here.
# Additional items can be added by adding a dictionary key similar to the 'config' key.
# [[ref]](http://docs.k8s-at-home.com/our-helm-charts/common-library-storage)
# @default -- See below
persistence:
  config:
    enabled: true
    type: configMap
    name: '{{ printf "%v-config" (include "common.names.fullname" .) }}'
    mountPath: /home/jovyan/.jupyter

# -- Settings injected by modeldynamics.ai
modeldynamics:
  internal:
    project:
      name: ""
